using EduZim.Application.Common.Interfaces;
using EduZim.Application.Common.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EduZim.Infrastructure.Billing;

public sealed class QuestPdfInvoiceGenerator : IInvoicePdfGenerator
{
    static QuestPdfInvoiceGenerator()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public Task<byte[]> GeneratePdfAsync(InvoicePdfModel model, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var pdf = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(header =>
                {
                    header.Item().Text("EduZim").SemiBold().FontSize(20);
                    header.Item().Text("Subscription invoice").FontSize(14).FontColor(Colors.Grey.Darken2);
                });

                page.Content().PaddingTop(1.5f, Unit.Centimetre).Column(column =>
                {
                    column.Spacing(8);
                    column.Item().Text($"Invoice ID: {model.InvoiceId}");
                    column.Item().Text($"Issued (UTC): {model.IssuedAtUtc:yyyy-MM-dd HH:mm}");
                    column.Item().Text($"School / tenant: {model.TenantName}");
                    column.Item().Text($"Billing cycle: {model.Cycle}");
                    column.Item().Text($"Students billed: {model.StudentCount}");
                    column.Item().Text($"Unit price: {model.UnitPrice:0.00} {model.Currency}");
                    column.Item().Text($"Total due: {model.TotalAmount:0.00} {model.Currency}").SemiBold();
                    if (!string.IsNullOrWhiteSpace(model.PaymentProviderReference))
                        column.Item().Text($"Payment reference: {model.PaymentProviderReference}");
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by EduZim — ");
                    text.Span(model.TenantId.ToString());
                });
            });
        }).GeneratePdf();

        return Task.FromResult(pdf);
    }
}
